feat: Rework of tokens (dark mode foundation)
warp-ds/css pull request #174
Opened 2024-03-01 15:40 UTC by magnuh

Source of truth: https://docs.google.com/spreadsheets/d/1Q-Tr_dwJVfxgh3527IFjXQKqtnPPM42QeIr-M6q-zu8

2024-03-04 14:21 UTC, felicia-haggqvist reviewed
Noticed this when testing the vue-repo with these css-changes that does not look like this before these css-changes: 
<img width="233" alt="Skärmavbild 2024-03-04 kl  15 13 24" src="https://github.com/warp-ds/css/assets/144792260/eab73964-3c0e-4bce-9fe0-7297e4873f4e">
<br>
<img width="203" alt="Skärmavbild 2024-03-04 kl  15 13 14" src="https://github.com/warp-ds/css/assets/144792260/80c9b03f-7217-4e1f-aec7-a25d0a9ee76c">
<br>
<img width="270" alt="Skärmavbild 2024-03-04 kl  15 13 05" src="https://github.com/warp-ds/css/assets/144792260/356dfd9e-7ba9-4c05-804d-a73d2e6785ee">
<br>
<img width="917" alt="Skärmavbild 2024-03-04 kl  15 11 12" src="https://github.com/warp-ds/css/assets/144792260/a54b0abc-0bc9-4287-9785-356c54b1bffa">

2024-03-04 14:52 UTC, magnuh commented
> Noticed that the background-color and text-color have changed when testing the vue-repo with these css-changes 

Did you include the new brand.css files with the new tokens?

2024-03-04 15:16 UTC, felicia-haggqvist commented
> > Noticed that the background-color and text-color have changed when testing the vue-repo with these css-changes
> 
> Did you include the new brand.css files with the new tokens?

Whoops! No! 🙈 😄

2024-03-04 15:33 UTC, felicia-haggqvist approved these changes

2024-03-05 14:15 UTC, BalbinaK commented on tokens/finn.no/deprecated.yml
> +          active: green-200
The document you linked to seems to have been updated and those tokens are not needed:
https://docs.google.com/spreadsheets/d/1Q-Tr_dwJVfxgh3527IFjXQKqtnPPM42QeIr-M6q-zu8/edit#gid=888578831&range=68:70

2024-03-05 14:28 UTC, BalbinaK approved these changes
LGTM!

2024-03-07 09:43 UTC, BalbinaK commented on component-classes/index.js
> +  neutral: 's-bg-sunken',
I tried testing these changes in React by linking them there + copying over missing tokens, but the `--w-s-color-background-sunken` token that this class was looking for was missing.
<img width="378" alt="Screenshot 2024-03-07 at 10 42 58" src="https://github.com/warp-ds/css/assets/41303231/da9ca224-ec49-4b26-9ef6-5d9a8fcbcb21">

2024-03-07 09:52 UTC, BalbinaK requested changes
I tried testing these changes in React by linking them there + copying over missing tokens, but the `--w-s-color-background-sunken` token that this class was looking for was missing.
<img width="378" alt="Screenshot 2024-03-07 at 10 42 58" src="https://github.com/warp-ds/css/assets/41303231/da9ca224-ec49-4b26-9ef6-5d9a8fcbcb21">

2024-03-07 09:52 UTC, BalbinaK commented on component-classes/index.js
> +  neutral: 's-bg-sunken',
I tried testing these changes in React by linking them there + copying over missing tokens, but the `--w-s-color-background-sunken` token that this class was looking for was missing.
<img width="378" alt="Screenshot 2024-03-07 at 10 42 58" src="https://github.com/warp-ds/css/assets/41303231/da9ca224-ec49-4b26-9ef6-5d9a8fcbcb21">

2024-03-15 12:06 UTC, BalbinaK approved these changes

2024-03-15 13:43 UTC, merged